# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Schrodinger"); Pkg.test("Schrodinger"; coverage=true)'
after_success:
  # deploy documentation
  - julia -e 'Pkg.add("Documenter"); Pkg.add("PyPlot"); Pkg.add("Plots")'
  - julia -e 'cd(Pkg.dir("Schrodinger")); include(joinpath("docs", "make.jl"))'
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Schrodinger")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  ## push coverage results to Codecov
  #- julia -e 'cd(Pkg.dir("Schrodinger")); Pkg.add("Coverage"); using Coverage; #Codecov.submit(Codecov.process_folder())'
